### ISSUE TITLE
I cannot log into workbench: "An error has occurred and you have been logged out: unknown_error: retry your request"

### ISSUE THREAD

**Issue by ArmareoGOOG** [forceworkbench/forceworkbench#821] opened 2019-08-08 20:37 UTC
**Describe the bug**
I am not able to log-in and receive the error "An error has occurred and you have been logged out: unknown_error: retry your request"

**Additional context**
This is an issue on Stack Exchange here, currently 103 ppl viewing it TODAY: https://salesforce.stackexchange.com/questions/272956/i-cannot-log-into-workbench/272960#272960

**To Reproduce**
1. Go to https://forceworkbench.appspot.com/login.php
2. Click on the OAuth radio button
3. On Salesforce log-in page, enter username and password.
4. Error displays on the page and after 5 seconds the page reverts back to the original, standard log-in screen.

**Expected behavior**
I am able to log-in and use the product.

**Screenshots**
https://screenshot.googleplex.com/H98CbOhAKoN

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76

**Comment by ntotten** [comment] 2019-08-09 11:12
Duplicate of #820

**Closed by ntotten** 2019-08-09 11:12 UTC
